printWidth: 100
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: consistent
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
